### ISSUE TITLE
can :command be defined in config.json?

### ISSUE THREAD

**Issue by mph070770** [alexbain/lirc_web#16]
I'm using lirc_web to control an IR dimmer switch. I have 4 settings currently defined - KEY_PROG1 to KEY_PROG4. I would like to be define that, for example:

KEY_PROG1 is OFF
KEY_PROG2 is LOW
KEY_PROG3 is medium
KEY_PROG4 is FULL

and then call these from http://url/remotes/my_remote/OFF    etc

Is that possible? I've tried setting these labels up in config.json but it doesn't appear to work.

Thanks

**Comment by alexbain** [comment]
No, :command cannot be defined in config.json right now. Only the display label shown in the UI.

Please feel free to open a merge request with support for this feature if you'd like to see it.
