### ISSUE TITLE
SIMULATE command support

### ISSUE THREAD

**Issue by vivgarot** [alexbain/lirc_web#21]
Would it be possible to add support for SIMULATE commands ?

I am happy to help with testing but useless at coding

**Comment by alexbain** [comment]
@vivgarot `SIMULATE` is already supported in `lirc_node` (https://github.com/alexbain/lirc_node/blob/master/lib/irsend.js#L44). 

Feel free to reopen if you were looking for something beyond `lirc_node` support.

**Comment by vivgarot** [comment]
Actually I would love to see SIMULATE support in lirc_web. Works great in lirc_node but as for now lirc_web is not able to send a SIMULATE command.
