### ISSUE TITLE
No templates/index.swig copied during global install, resulting in error on webpage.

### ISSUE THREAD

**Issue by smccy** [alexbain/lirc_web#25]
Following Installation Method 1: 

    Method 1: global installation, lirc_web available as binary

    npm install -g lirc_web
    lirc_web
    Note that you may need to run the npm install command as sudo.

The install took 20 seconds max on my RPi 2
My terminal output is this:

    pi@raspberrypi ~ $ sudo npm -g install lirc_web
    npm WARN deprecated swig@0.13.5: v1.0.0 is a complete rewrite of Swig from the ground up.        
    Previous versions are no longer supported
    /usr/local/bin/lirc_web -> /usr/local/lib/node_modules/lirc_web/app.js
    lirc_web@0.2.1 /usr/local/lib/node_modules/lirc_web
    ├── consolidate@0.11.0
    ├── lirc_node@0.0.4
    ├── swig@0.13.5 (underscore@1.8.3)
    └── express@3.0.6 (methods@0.0.1, fresh@0.1.0, cookie-signature@0.0.1, range-par
    ser@0.0.4, buffer-crc32@0.1.1, cookie@0.0.5, commander@0.6.1, mkdirp@0.3.3, debu
    g@2.2.0, send@0.1.0, connect@2.7.2)

    pi@raspberrypi ~ $ lirc_web
    DEBUG: { [Error: Cannot find module '/home/pi/.lirc_web_config.json'] code: 'MOD                 
    ULE_NOT_FOUND' }
    WARNING: Cannot find config.json!
    Open Source Universal Remote UI + API has started on port 3000 (http).

(The warning at the end is fine, since I haven't created the config.json file.)

lirc_web runs, but when I access it via the website I get this:

    Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/lirc_web/templates/index.swig'
        at Error (native)
        at Object.fs.openSync (fs.js:500:18)
        at Object.fs.readFileSync (fs.js:352:15)
        at getSingle (/usr/local/lib/node_modules/lirc_web/node_modules/swig/lib/swig.js:152:19)
        at get (/usr/local/lib/node_modules/lirc_web/node_modules/swig/lib/swig.js:159:7)
        at Object.exports.compileFile (/usr/local/lib/node_modules/lirc_web/node_modules/swig/lib/swig.js:177:7)
        at Object. (/usr/local/lib/node_modules/lirc_web/app.js:14:15)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)

Following the error on the first line, there is no folder named

    /usr/local/lib/node_modules/lirc_web/templates

Add that folder (and index.swig file) manually from the source, and viola - Working LIRC_WEB

**Comment by alexbain** [comment]
This should be fixed in `v.0.2.2`.

Thanks for catching that!
