### ISSUE TITLE
Linter should lint test JS files, too

### ISSUE THREAD

**Issue by alexbain** [alexbain/lirc_web#27]
Currently the linter doesn't ensure the test files conform to the JS styleguide. Let's fix that - all JS files (tests included) should be linted.

**Comment by alexbain** [comment]
This will be fixed in the `macrostraction` branch

**Comment by OvisMaximus** [comment]
Since I did lots of stuff this weekend, I needed the linting and some automatism to continuously show lint results. Pls see the pull request 31.

**Comment by alexbain** [comment]
Works great, thank you. I'll clean up my `macrostraction` branch to incorporate these changes.
