### ISSUE TITLE
Remove external jQuery dependency from test suite

### ISSUE THREAD

**Issue by alexbain** [alexbain/lirc_web#28]
Currently we have an external network request that fetches jQuery. This slows down the tests and cause them to sporadically fail due to timeouts.

Let's include the version of jQuery that already exists in the project instead of trying to include a remote version. This will also ensure the jQuery versions match.

**Comment by OvisMaximus** [comment]
I found these copies of jquery in the node modules:
underscore.string/test/test_underscore/vendor/jquery.js
grunt-legacy-log/node_modules/underscore.string/test/test_underscore/vendor/jquery.js
grunt-legacy-log-utils/node_modules/underscore.string/test/test_underscore/vendor/jquery.js
tiny-lr-fork/node_modules/qs/test/browser/jquery.js
qs/test/browser/jquery.js

I'm not sure which one of these to use if any of them at all: supposed we change the dependency, then a part of the test suite is gone.

If a own copy of it like test/jquery.js is not an option, perhaps a auto download in one of the build scripts is the way to go? Keeping it simple I'd just use a static, checked in copy of the library.

**Comment by OvisMaximus** [comment]
The best I could do was to add a dependency to jquery and use the file that comes with this distribution. Note that this works with jquery up to version 2.1.0. I'll create a pull request with the fix.

**Comment by alexbain** [comment]
I think adding the jQuery dependency was the right idea. Thanks for fixing this!
