### ISSUE TITLE
When installed globally and initialized with upstart, config file is not found

### ISSUE THREAD

**Issue by codeandcountry** [alexbain/lirc_web#40]
Hey Alex, nice work with this project, you've done a great job. Ran across this bug today:
- lirc_web installed globally
- .lirc_web_config.json in my home directory
- initializing using your example standalone_upstart.conf

lirc_web fails to find the config because, debug in log reads: DEBUG: { [Error: Cannot find module 'undefined/.lirc_web_config.json'] code: "MODULE_NOT_FOUND"

looks like it originates here, where process.env.HOME is seemingly not available:
https://github.com/alexbain/lirc_web/blob/master/app.js#L44

thanks again for this great project.

**Comment by alexbain** [comment]
Thanks for reporting and fixing this.
