### ISSUE TITLE
Re-init if lircd timed out

### ISSUE THREAD

**Issue by f00f** [alexbain/lirc_web#8]
I'm using lirc_web on raspbmc, which causes some troubles my starting its own lircd or eventlircd. When doing some things wrong I would end up with only one remote, "timeout", in the API.

**How to reproduce:**
If lircd is not properly started when the API is first accessed then remotes will contain "timeout".

**How to fix it:**
In that case, lirc_node.init() should be called again, I guess.
I'm still undecided if I would build that into lirc_web or lirc_node. One would need a flag indicating a successful init and a call to init at the beginning of every lirc_web (or lirc_node, resp.) function.

I'm willing to try patching it, just let me know your thoughts about it.

**Comment by alexbain** [comment]
Thanks for fixing this - I merged in your merge request today.
